// src/components/records/SaveRecord.tsx
import React, {useState, useEffect} from 'react';
import {Modal, Button, Form} from 'components/bootstrap';
import Flatpickr from 'react-flatpickr';

import config from 'config';
import validationHelper from 'helpers/validationHelper';

import NumberInput from 'components/common/NumberInput';
import TextAreaInput from 'components/common/TextAreaInput';
import SelectInput from 'components/common/SelectInput';

const dateOptions = {dateFormat: config.format.datePicker};

interface Props {
  record: any;
  categories: any[];
  save: () => void;
  close: () => void;
  onChange: OnChangeHandler;
  visible?: boolean;
}

function SaveRecord({record, categories, save, close, onChange, visible}: Props) {
  const [errors, setErrors] = useState({categoryId: '', cost: '', note: ''});

  useEffect(() => {
    setErrors({categoryId: '', cost: '', note: ''});
  }, [record]);

  function formIsValid() {
    const errors = {
      categoryId: '',
      cost: '',
      note: ''
    };

    if (!record.categoryId) {
      errors.categoryId = 'Category field is required.';
    }

    if (!record.cost) {
      errors.cost = 'Cost field is required.';
    }

    if (!record.note) {
      errors.note = 'Note field is required.';
    }

    setErrors(errors);

    return validationHelper.isEmptyErrorObject(errors);
  }

  function onSave() {
    if (!formIsValid()) return;

    save();
  }

  function onDateChange(date) {
    onChange('date', new Date(date));
  }

  function render() {
    if (!record) return null;

    const title = record.id ? 'Edit Record' : 'Add New Record';

    const cost = record.cost ? parseFloat(record.cost) : 0;

    const categoryOptions = categories.map(category => {
      return {value: category.id, label: category.title};
    });

    return (
      <Modal show={visible} backdrop="static" onHide={close}>
        <Modal.Header closeButton>{title}</Modal.Header>
        <Modal.Body>
          <Form.Group>
            <Form.Label>Date:</Form.Label>

            <div>
              <Flatpickr value={record.date} options={dateOptions} onChange={onDateChange} />
            </div>
          </Form.Group>

          <NumberInput name="cost" label="Cost" value={cost} onChange={onChange} error={errors.cost} />

          <SelectInput
            name="categoryId"
            label="Category"
            value={record.categoryId}
            options={categoryOptions}
            onChange={onChange}
            error={errors.categoryId}
          />

          <TextAreaInput
            name="note"
            label="Note:"
            value={record.note}
            onChange={onChange}
            placeholder="Note"
            error={errors.note}
          />
        </Modal.Body>
        <Modal.Footer>
          <Button variant="primary" onClick={onSave}>
            Save
          </Button>
          <Button variant="secondary" onClick={close}>
            Cancel
          </Button>
        </Modal.Footer>
      </Modal>
    );
  }

  return render();
}

export default SaveRecord;

// src/components/records/SaveRecord.vue
<template>
  <modal :visible="showModal" :title="title" :closeTitle="'Cancel'" :onClose="onCloseClick" :onSave="onSaveClick">
    <div slot="body">
      <div class="form-group">
        <label>Date</label>

        <date-picker v-model="record.date" :options="dateOptions"></date-picker>
      </div>

      <div class="form-group">
        <label for="record-title">Cost</label>

        <input type="number" class="form-control" id="record-title" placeholder="Cost" name="cost"
               :class="{'input': true, 'is-danger': errors.has('cost') }" v-validate="'required|min_value:0.01'" v-model="record.cost" />

        <span v-show="errors.has('cost')" class="help is-danger">{{ errors.first('cost') }}</span>
      </div>

      <div class="form-group">
        <label>Category</label>

        <select v-model="record.categoryId" class="form-control" name="category"
                :class="{'select': true, 'is-danger': errors.has('category') }" v-validate="'required'">
          <option v-for="category in categories" :value="category.id">{{category.title}}</option>
        </select>

        <span v-show="errors.has('category')" class="help is-danger">{{ errors.first('category') }}</span>
      </div>

      <div class="form-group">
        <label for="record-note">Note</label>

        <textarea class="form-control" id="record-note" placeholder="Note" rows="4" name="note"
                  :class="{'textarea': true, 'is-danger': errors.has('note') }" v-validate="'required'"
                  v-model="record.note">
        </textarea>

        <span v-show="errors.has('note')" class="help is-danger">{{ errors.first('note') }}</span>
      </div>
    </div>
  </modal>
</template>

<script src="./SaveRecord.vue.js"></script>
