// src/components/auth/ActivationPage.vue
<template>
  <div class="container">
    <div class="col-xs-8 col-xs-offset-0 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <h1>Activation Page</h1>

      <br/>

      <div v-if="activationData.message" v-bind:class="alertClass">{{activationData.message}}</div>

      <hr />

      <p>Redirect to login page: <router-link to="/login">Login</router-link></p>
    </div>
  </div>
</template>

<script src="./ActivationPage.vue.js"></script>

// src/components/auth/activation/ActivationPage.tsx
import {useEffect, useState} from 'react';
import {Link, useParams} from 'react-router-dom';

import {Col, Container, Row} from 'components/bootstrap';

import userActions from 'actions/userActions';

import {useAppDispatch} from 'hooks';

import * as styled from './ActivationPage.styled';

function ActivationPage() {
  const dispatch = useAppDispatch();

  const {token} = useParams();

  const [activationData, setActivationData] = useState({message: '', status: ''});

  useEffect(() => {
    activateAccount();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function activateAccount() {
    const data: any = await dispatch(userActions.activateUserAccount(token));

    if (data) setActivationData(data);
  }

  const status = activationData.status;

  return (
    <Container>
      <Row>
        <Col sm={{span: 6, offset: 3}}>
          <h1 className="mb-3">Activation Page</h1>

          <br />

          {activationData.message && (
            <styled.alert
              className="alert"
              isSuccess={status === 'success'}
              isWarning={status === 'warning'}
              isError={status === 'error'}
            >
              {activationData.message}
            </styled.alert>
          )}

          <hr />

          <p>
            Redirect to login page: <Link to="/login">Login</Link>
          </p>
        </Col>
      </Row>
    </Container>
  );
}

export default ActivationPage;
