// src/components/auth/ActivationPage.tsx
import React, {useState, useEffect} from 'react';
import {useDispatch} from 'react-redux';
import classnames from 'classnames';
import {Link, useParams} from 'react-router-dom';
import {Container, Row, Col} from 'bootstrap';

import {activateUserAccount} from 'actions/userActions';

function ActivationPage() {
  const dispatch = useDispatch();
  let {token} = useParams();

  const [activationData, setActivationData] = useState({message: '', status: ''});

  useEffect(() => {
    activateAccount();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const activateAccount = async () => {
    let data: any = await dispatch(activateUserAccount(token));

    if (data) setActivationData(data);
  };

  let status = activationData.status;

  let alertClass = classnames({
    alert: true,
    'alert-danger': status === 'error',
    'alert-success': status === 'success',
    'alert-warning': status === 'warning'
  });

  return (
    <Container>
      <Row>
        <Col sm={{span: 6, offset: 3}}>
          <h1>Activation Page</h1>

          <br />

          {activationData.message && <div className={alertClass}>{activationData.message}</div>}

          <hr />

          <p>
            Redirect to login page: <Link to="/login">Login</Link>
          </p>
        </Col>
      </Row>
    </Container>
  );
}

export default ActivationPage;

// src/components/auth/ActivationPage.vue
<template>
  <div class="container">
    <div class="col-xs-8 col-xs-offset-0 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <h1>Activation Page</h1>

      <br/>

      <div v-if="activationData.message" v-bind:class="alertClass">{{activationData.message}}</div>

      <hr />

      <p>Redirect to login page: <router-link to="/login">Login</router-link></p>
    </div>
  </div>
</template>

<script src="./ActivationPage.vue.js"></script>
