// src/components/auth/LoginPage.tsx
import {isEmpty} from 'lodash';
import {useEffect, useState} from 'react';
import {Link, useNavigate} from 'react-router-dom';

import {Button, Col, Container, Row} from 'components/bootstrap';

import userActions from 'actions/userActions';

import {useAppDispatch, useAppSelector} from 'hooks';

import validationHelper from 'helpers/validationHelper';

import AppIcon from 'components/common/AppIcon';
import TextInput from 'components/common/TextInput';

function LoginPage() {
  const currentUser = useAppSelector(state => state.user.current);

  const dispatch = useAppDispatch();
  const navigate = useNavigate();

  const [user, setUser] = useState({email: '', password: ''});

  const [errors, setErrors] = useState({email: '', password: ''});

  useEffect(() => {
    if (!isEmpty(currentUser)) navigate('/');
  });

  function onChange(field: string, value) {
    const newUser = {...user};

    newUser[field] = value;

    setUser(newUser);
  }

  function loginFormIsValid() {
    const errors = {
      email: '',
      password: ''
    };

    if (!user.email) {
      errors.email = 'Email field is required.';
    } else if (!validationHelper.isValidEmail(user.email)) {
      errors.email = 'Email is not valid.';
    }

    if (!user.password) {
      errors.password = 'Password field is required.';
    }

    setErrors(errors);

    return validationHelper.isEmptyErrorObject(errors);
  }

  async function login(e) {
    if (e) e.preventDefault();

    if (!loginFormIsValid()) return;

    await dispatch(userActions.loginUser(user));

    await dispatch(userActions.getCurrentUser());

    if (!isEmpty(user)) navigate('/records');
  }

  return (
    <Container>
      <Row>
        <Col sm={{span: 6, offset: 3}}>
          <h1 className="mb-5">
            <AppIcon icon="sign-in" /> Login
          </h1>

          <form onSubmit={login}>
            <TextInput
              name="email"
              label="Email"
              type="email"
              value={user.email}
              onChange={onChange}
              placeholder="Email"
              error={errors.email}
            />

            <TextInput
              name="password"
              label="Password"
              type="password"
              value={user.password}
              onChange={onChange}
              placeholder="Password"
              error={errors.password}
            />

            <Button variant="warning" size="lg" type="submit" onClick={login}>
              Login
            </Button>
          </form>

          <hr />

          <Link to="/password-forgot">Forgot your password?</Link>

          <hr />

          <p>
            Need an account? <Link to="/sign-up">Sign Up</Link>
          </p>
        </Col>
      </Row>
    </Container>
  );
}

export default LoginPage;

// src/components/auth/LoginPage.vue
<template>
  <div class="container">
    <div class="col-xs-8 col-xs-offset-0 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <h1><span class="fa fa-sign-in" /> Login</h1>

      <form @submit.prevent="validateBeforeSubmit" novalidate>
        <div class="form-group">
          <label htmlFor="email">Email</label>

          <div class="field">
            <input type="email" id="email" name="email" class="form-control" placeholder="Email"
                   v-validate="'required|email'" :class="{'input': true, 'is-danger': errors.has('email') }"
                   v-model="userData.email" />

            <span v-show="errors.has('email')" class="help is-danger">{{ errors.first('email') }}</span>
          </div>
        </div>

        <div class="form-group">
          <label htmlFor="password">Password</label>

          <div class="field">
            <input type="password" id="password" name="password" class="form-control" placeholder="Password"
                   v-validate="'required'" :class="{'input': true, 'is-danger': errors.has('password') }"
                   v-model="userData.password" />

            <span v-show="errors.has('password')" class="help is-danger">{{ errors.first('password') }}</span>
          </div>
        </div>

        <button type="submit" class="btn btn-warning btn-lg">Login</button>
      </form>

      <hr />

      <router-link to="/password-forgot">Forgot your password?</router-link>

      <hr />

      <p>Need an account? <router-link to="/signup">Signup</router-link></p>
    </div>
  </div>
</template>

<script src="./LoginPage.vue.js"></script>
