// src/components/auth/PasswordForgotPage.tsx
import React, {useState} from 'react';
import {useDispatch} from 'react-redux';
import {Link} from 'react-router-dom';
import {Container, Row, Col, Button} from 'components/bootstrap';

import userActions from 'actions/userActions';

import validationHelper from 'helpers/validationHelper';

import TextInput from 'components/common/TextInput';

function PasswordForgotPage() {
  const dispatch = useDispatch();

  const [email, setEmail] = useState('');

  const [errors, setErrors] = useState({email: ''});

  function onChange(field: string, value: string) {
    setEmail(value);
  }

  function forgotFormIsValid() {
    let errors = {
      email: ''
    };

    if (!email) {
      errors.email = 'Email field is required.';
    } else if (!validationHelper.isValidEmail(email)) {
      errors.email = 'Email is not valid.';
    }

    setErrors(errors);

    return validationHelper.isEmptyErrorObject(errors);
  }

  async function resetPassword() {
    if (!forgotFormIsValid()) return;

    await dispatch(userActions.forgotPassword(email));
  }

  return (
    <Container>
      <Row>
        <Col sm={{span: 6, offset: 3}}>
          <h1>Reset Password</h1>

          <TextInput
            name="email"
            label="Email"
            type="email"
            value={email}
            onChange={onChange}
            placeholder="Email"
            error={errors.email}
          />

          <Button variant="warning" size="lg" onClick={resetPassword}>
            Reset Password
          </Button>

          <hr />

          <p>
            Already have an account? <Link to="/login">Login</Link>
          </p>
        </Col>
      </Row>
    </Container>
  );
}

export default PasswordForgotPage;

// src/components/auth/PasswordForgotPage.vue
<template>
  <div class="container">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Reset Password</h1>

      <form @submit.prevent="validateBeforeSubmit" novalidate>
        <div class="form-group">
          <label htmlFor="email">Email</label>

          <div class="field">
            <input type="email" id="email" name="email" class="form-control" placeholder="Email"
                   v-validate="'required|email'" :class="{'input': true, 'is-danger': errors.has('email') }"
                   v-model="email" />

            <span v-show="errors.has('email')" class="help is-danger">{{ errors.first('email') }}</span>
          </div>
        </div>

        <button type="submit" class="btn btn-warning btn-lg">Reset Password</button>
      </form>

      <hr />

      <p>Already have an account? <router-link to="/login">Login</router-link></p>
    </div>
  </div>
</template>

<script src="./PasswordForgotPage.vue.js"></script>
