// src/components/auth/SignUpPage.tsx
import React, {useState} from 'react';
import {useDispatch} from 'react-redux';
import {Link, useHistory} from 'react-router-dom';
import {Container, Row, Col, Button} from 'components/bootstrap';

import {signUp} from 'actions/userActions';

import validationHelper from 'helpers/validationHelper';
import uiHelper from 'helpers/uiHelper';

import AppIcon from 'components/common/AppIcon';
import {TextInput} from 'components/common/TextInput';

function SignUpPage() {
  const dispatch = useDispatch();
  let history = useHistory();

  const [user, setUser] = useState({firstName: '', lastName: '', email: '', password: '', confirmPassword: ''});

  const [errors, setErrors] = useState({firstName: '', lastName: '', email: '', password: '', confirmPassword: ''});

  function onChange(field: string, value) {
    let newUser = {...user};

    newUser[field] = value;

    setUser(newUser);
  }

  function signUpFormIsValid() {
    let errors = {
      firstName: '',
      lastName: '',
      email: '',
      password: '',
      confirmPassword: ''
    };

    if (!user.firstName) {
      errors.firstName = 'First Name field is required.';
    }

    if (!user.lastName) {
      errors.lastName = 'Last Name field is required.';
    }

    if (!user.email) {
      errors.email = 'Email field is required.';
    } else if (!validationHelper.isValidEmail(user.email)) {
      errors.email = 'Email is not valid.';
    }

    if (!user.password) {
      errors.password = 'Password field is required.';
    }

    if (!user.confirmPassword) {
      errors.confirmPassword = 'Please confirm the password.';
    }

    if (user.password && user.confirmPassword && user.password !== user.confirmPassword) {
      errors.confirmPassword = 'Wrong password.';
    }

    setErrors(errors);

    return validationHelper.isEmptyErrorObject(errors);
  }

  async function onSignUp() {
    if (!signUpFormIsValid()) return;

    let response: any = await dispatch(signUp(user));

    if (response && response.message) {
      uiHelper.showMessage(response.message);

      history.push('/login');
    }
  }

  return (
    <Container>
      <Row>
        <Col sm={{span: 6, offset: 3}}>
          <h1>
            <AppIcon icon="sign-in" /> Sign Up
          </h1>

          <TextInput
            name="firstName"
            label="First Name"
            value={user.firstName}
            onChange={onChange}
            placeholder="First Name"
            error={errors.firstName}
          />

          <TextInput
            name="lastName"
            label="Last Name"
            value={user.lastName}
            onChange={onChange}
            placeholder="Last Name"
            error={errors.lastName}
          />

          <TextInput
            name="email"
            label="Email"
            type="email"
            value={user.email}
            onChange={onChange}
            placeholder="Email"
            error={errors.email}
          />

          <TextInput
            name="password"
            label="Password"
            type="password"
            value={user.password}
            onChange={onChange}
            placeholder="Password"
            error={errors.password}
          />

          <TextInput
            name="confirmPassword"
            label="Confirm Password"
            type="password"
            value={user.confirmPassword}
            onChange={onChange}
            placeholder="Confirm Password"
            error={errors.confirmPassword}
          />

          <Button variant="warning" size="lg" onClick={onSignUp}>
            Sign Up
          </Button>

          <hr />

          <p>
            Already have an account? <Link to="/login">Login</Link>
          </p>
        </Col>
      </Row>
    </Container>
  );
}

export default SignUpPage;

// src/components/auth/SignUpPage.vue
<template>
  <div class="container">
    <div class="col-xs-8 col-xs-offset-0 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <h1><span class="fa fa-sign-in" /> Signup</h1>

      <form @submit.prevent="validateBeforeSubmit" novalidate>
        <div class="form-group">
          <label htmlFor="first-name">First Name</label>

          <div class="field">
            <input type="text" id="first-name" name="firstName" class="form-control" placeholder="First Name"
                   v-validate:firstName="'required'" :class="{'input': true, 'is-danger': errors.has('firstName') }"
                   v-model="userData.firstName" />

            <span v-show="errors.has('firstName')" class="help is-danger">{{ errors.first('firstName') }}</span>
          </div>
        </div>

        <div class="form-group">
          <label htmlFor="last-name">Last Name</label>

          <div class="field">
            <input type="text" id="last-name" name="lastName" class="form-control" placeholder="Last Name"
                   v-validate:lastName="'required'" :class="{'input': true, 'is-danger': errors.has('lastName') }"
                   v-model="userData.lastName" />

            <span v-show="errors.has('lastName')" class="help is-danger">{{ errors.first('lastName') }}</span>
          </div>
        </div>

        <div class="form-group">
          <label htmlFor="email">Email</label>

          <div class="field">
            <input type="email" id="email" name="email" class="form-control" placeholder="Email"
                   v-validate:email="'required|email'" :class="{'input': true, 'is-danger': errors.has('email') }"
                   v-model="userData.email" />

            <span v-show="errors.has('email')" class="help is-danger">{{ errors.first('email') }}</span>
          </div>
        </div>

        <div class="form-group">
          <label htmlFor="password">Password</label>

          <div class="field">
            <input type="password" id="password" name="password" class="form-control" placeholder="Password"
                   v-validate:password="'required'" :class="{'input': true, 'is-danger': errors.has('password') }"
                   v-model="userData.password" />

            <span v-show="errors.has('password')" class="help is-danger">{{ errors.first('password') }}</span>
          </div>
        </div>

        <div class="form-group">
          <label htmlFor="confirm-password">Confirm Password</label>

          <div class="field">
            <input type="password" id="confirm-password" name="confirmPassword" class="form-control" placeholder="Confirm Password"
                   v-validate:confirmPassword="'required'" :class="{'input': true, 'is-danger': errors.has('confirmPassword') }"
                   v-model="userData.confirmPassword" />

            <span v-show="errors.has('confirmPassword')" class="help is-danger">{{ errors.first('confirmPassword') }}</span>
          </div>
        </div>

        <button type="submit" class="btn btn-warning btn-lg">Signup</button>
      </form>

      <hr />

      <p>Already have an account? <router-link to="/login">Login</router-link></p>
    </div>
  </div>
</template>

<script src="./SignUpPage.vue.js"></script>
